### ISSUE TITLE
Migrate from legacy dependency handling

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-dashboard#2549]
As #2533 will be merged soon we added `legacy-peer-deps=true` to `.npmrc` file. According to npm [docs](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps), this is not recommended so we should fix our dependencies.

Stuff to migrate:

- [ ] Storybook to v6 (#2591)
- [ ] Jest or #migrate to Vitest (#2740)
- [ ] Apollo - blocked by https://github.com/saleor/saleor-sdk/issues/170
- [ ] Small updates - see previous Node 16 update (#2385) or wait until we clean up not used dependencies
