### ISSUE TITLE
Fix ESLint rules

### ISSUE THREAD

**Issue by Droniu** [saleor/saleor-dashboard#3813]
### What I'm trying to achieve
Currently ESLint gives us a lot of warnings, tracked by `npm run lint:check`

### Describe a proposed solution
Rules should be resolved one by one
```
    "@typescript-eslint/consistent-type-imports": "off", // autofix, large - issue 3847, TBD with team - imo yes
    "@typescript-eslint/no-confusing-void-expression": "off", // autofix, large, TBD with team - imo off
    "@typescript-eslint/no-unnecessary-type-assertion": "off", // autofix, small - issue 3926
    "@typescript-eslint/prefer-reduce-type-parameter": "off", // autofix, small - issue 3927
    "@typescript-eslint/promise-function-async": "off", // autofix, medium - issue 3928
    "@typescript-eslint/return-await": "off", // autofix, small - issue 3929
    "@typescript-eslint/space-before-function-paren": "off", // tiny (3860)
    "@typescript-eslint/strict-boolean-expressions": "off", // autofix, large, off - requires strict null checks
    "multiline-ternary": "off", // tiny (3860)
    "no-extra-boolean-cast": "off", // autofix, medium - issue 3930
    "@typescript-eslint/await-thenable": "warn", // small - issue 3859
    "@typescript-eslint/ban-ts-comment": "warn", // tiny (3860)
    "@typescript-eslint/ban-types": "warn", // medium (3861)
    "@typescript-eslint/consistent-type-assertions": "warn", // tiny - issue 3862
    "@typescript-eslint/explicit-function-return-type": "off", // large - off
    "@typescript-eslint/naming-convention": "warn", // tiny (3860)
    "@typescript-eslint/no-base-to-string": "warn", // small - issue 3920
    "@typescript-eslint/no-dynamic-delete": "warn", // tiny (3860)
    "@typescript-eslint/no-floating-promises": "warn",// TBD with team
    "@typescript-eslint/no-invalid-void-type": "warn",// small - issue 3925
    "@typescript-eslint/no-misused-promises": "warn",// TBD with team
    "@typescript-eslint/no-non-null-asserted-optional-chain": "warn", // tiny (3860)
    "@typescript-eslint/no-non-null-assertion": "warn", // small - issue 3923
    "@typescript-eslint/no-redeclare": "warn", // small - isssue 3921
    "@typescript-eslint/prefer-nullish-coalescing": "warn", // large - off - reconsider when strict null migration is finished
    "@typescript-eslint/prefer-optional-chain": "warn", // small - issue 3919
    "@typescript-eslint/restrict-plus-operands": "warn", // small - issue 3918
    "@typescript-eslint/restrict-template-expressions": "warn", // small - issue 3917
    "array-callback-return": "warn", // tiny (3860)
    "import/export": "warn", // tiny (3860)
    "n/no-callback-literal": "warn", // tiny (3860)
    "no-case-declarations": "warn", // small - issue 3916
    "no-empty-pattern": "warn", // tiny (3860)
    "no-fallthrough": "warn", // tiny (3860)
    "no-new": "warn", // tiny (3860)
    "no-prototype-builtins": "warn", // tiny (3860)
    "no-unreachable": "warn", // tiny (3860)
    "no-useless-catch": "warn", // tiny (3860)
    "no-useless-escape": "warn", // tiny (3860)
    "prefer-promise-reject-errors": "warn", // tiny (3860)
    "react/display-name": "warn", // small - issue 3915
    "react/jsx-key": "warn", // small - issue 3914
    "react/prop-types": "warn", // medium - turn off, I think we don't need extra validation
    "symbol-description": "warn" // small  - issue 3913
```

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/3847
- [ ] https://github.com/saleor/saleor-dashboard/issues/3848
- [ ] https://github.com/saleor/saleor-dashboard/issues/3859
- [ ] https://github.com/saleor/saleor-dashboard/issues/3860
- [ ] https://github.com/saleor/saleor-dashboard/issues/3861
- [ ] https://github.com/saleor/saleor-dashboard/issues/3862
- [ ] https://github.com/saleor/saleor-dashboard/issues/3870
- [ ] https://github.com/saleor/saleor-dashboard/issues/3913
- [ ] https://github.com/saleor/saleor-dashboard/issues/3914
- [ ] https://github.com/saleor/saleor-dashboard/issues/3915
- [ ] https://github.com/saleor/saleor-dashboard/issues/3916
- [ ] https://github.com/saleor/saleor-dashboard/issues/3917
- [ ] https://github.com/saleor/saleor-dashboard/issues/3918
- [ ] https://github.com/saleor/saleor-dashboard/issues/3919
- [ ] https://github.com/saleor/saleor-dashboard/issues/3920
- [ ] https://github.com/saleor/saleor-dashboard/issues/3921
- [ ] https://github.com/saleor/saleor-dashboard/issues/3922
- [ ] https://github.com/saleor/saleor-dashboard/issues/3923
- [ ] https://github.com/saleor/saleor-dashboard/issues/3925
- [ ] https://github.com/saleor/saleor-dashboard/issues/3926
- [ ] https://github.com/saleor/saleor-dashboard/issues/3927
- [ ] https://github.com/saleor/saleor-dashboard/issues/3928
- [ ] https://github.com/saleor/saleor-dashboard/issues/3929
- [ ] https://github.com/saleor/saleor-dashboard/issues/3930
- [ ] https://github.com/saleor/saleor-dashboard/issues/4011
```
