### ISSUE TITLE
Release 3.15 issues

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#4107]
Let's create an list of issues of release 3.15
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4108
- [ ] https://github.com/saleor/saleor-dashboard/issues/4110
- [ ] https://github.com/saleor/saleor-dashboard/issues/4113
- [ ] https://github.com/saleor/saleor/issues/13757
```
