### ISSUE TITLE
[Epic] Migrate Cypress tests to Playwright

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#4134]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4384
- [ ] Add PW notification on slack
- [ ] https://github.com/saleor/saleor-dashboard/issues/4240
- [ ] https://github.com/saleor/saleor-dashboard/issues/4265
- [ ] https://github.com/saleor/saleor-dashboard/issues/4274
- [ ] https://github.com/saleor/saleor-dashboard/issues/4325
- [ ] https://github.com/saleor/saleor-dashboard/issues/4333
- [ ] https://github.com/saleor/saleor-dashboard/issues/4334
- [ ] https://github.com/saleor/saleor-dashboard/issues/4338
- [ ] https://github.com/saleor/saleor-dashboard/issues/4356
- [ ] https://github.com/saleor/saleor-dashboard/issues/4376
- [ ] https://github.com/saleor/saleor-dashboard/issues/4382
- [ ] https://github.com/saleor/saleor-dashboard/issues/4385
- [ ] https://github.com/saleor/saleor-dashboard/issues/4386
- [ ] https://github.com/saleor/saleor-dashboard/issues/4532
- [ ] https://github.com/saleor/saleor-dashboard/issues/4503
- [ ] https://github.com/saleor/saleor-dashboard/issues/4518
- [ ] https://github.com/saleor/saleor-dashboard/issues/4519
- [ ] https://github.com/saleor/saleor-dashboard/issues/4556
- [ ] https://github.com/saleor/saleor-dashboard/issues/4574
- [ ] https://github.com/saleor/saleor-dashboard/issues/4577
- [ ] https://github.com/saleor/saleor-dashboard/issues/4583
- [ ] https://github.com/saleor/saleor-dashboard/issues/4592
- [ ] https://github.com/saleor/saleor-dashboard/issues/4612
- [ ] https://github.com/saleor/saleor-dashboard/issues/4613
- [ ] https://github.com/saleor/saleor-dashboard/issues/4629
```
