### ISSUE TITLE
[Epic] Maintain e2e tests

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor-dashboard#4135]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4139
- [ ] Add Testmo config to the nightly workflow
- [ ] Check if critical tests are written correctly
- [ ] Compare if test cases are accurate with the test code
```
