### ISSUE TITLE
[Epic]: Data grid columns persistance

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#4457]
### Description of an epic

We can move around the the grid columns, but we cannot persist that state, so when the user refresh the page, moved columns are getting back to the default state.

```[tasklist]
### Tasks
- [ ] Investigate the grid persisntance as central mechanism
- [ ] Persistance for variants grid
- [ ] Persistance for product list grid
- [ ] Persistance for order list grid
```
