### ISSUE TITLE
Migrate products tests to playwright

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#4503]
Migrate product e2e tests from Cypress to Playwright:

AC:

- Migrated tests can be run on pr
- Test cases of migrated tests are updated
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/pull/4506
- [ ] https://github.com/saleor/saleor-dashboard/pull/4512
- [ ] https://github.com/saleor/saleor-dashboard/pull/4515
- [ ] https://github.com/saleor/saleor-dashboard/pull/4521
- [ ] https://github.com/saleor/saleor-dashboard/issues/4534
- [ ] https://github.com/saleor/saleor-dashboard/issues/4538
- [ ] https://github.com/saleor/saleor-dashboard/issues/4542
- [ ] https://github.com/saleor/saleor-dashboard/issues/4550
```
