### ISSUE TITLE
Migrate orders tests to playwright

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor-dashboard#4556]
Migrate orders e2e tests from Cypress to Playwright:

AC:

Migrated tests can be run on pr
Test cases of migrated tests are updated
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4557
- [ ] https://github.com/saleor/saleor-dashboard/issues/4562
- [ ] https://github.com/saleor/saleor-dashboard/issues/4563
- [ ] https://github.com/saleor/saleor-dashboard/issues/4567
- [ ] https://github.com/saleor/saleor-dashboard/issues/4573
```
