### ISSUE TITLE
[Feature]: Checkout and orders discounts

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor-dashboard#4616]
### Description of the feature

Users will be able to create rules that are related to checkout / making orders. By selecting conditions they are able to decide when given rule can be applied.

### _001 Creating checkout rule:_
- **Given** discounts are created
-  **When** user clicks add rule
   - _and_ picks "Checkout and orders" 
   - _and_ picks channel
   - _and_ fill the name
   - _and_ adds "purchase amount" condition
   - _and_ adds "usage limit" condition
   - _and_ clicks "save"
 - **Then** modal closes
    - _and_ user sees rule created for checkout with selected condition 

### _002 Editing checkout rule:_
- **Given** discounts is created
   - _and_ checkout rule is created
-  **When** user clicks edit rule (using pencil button)
   - _and_ change any field (condition, inputs, description)
   - _and_ clicks "save"
 - **Then** modal closes
    - _and_ user sees rule created for checkout with applied changes made within the modal

### _003 Checkout rule validation:_
- **Given** discounts is created
   - _and_ checkout rule is created
   - _or_ there is no rules created
-  **When** user clicks edit rule (using pencil button)
   - _or_ user creates new rule for checkout 
   - _and_ puts any wrong value (condition, input, description)
   - _and_ clicks "save"
 - **Then** user sees what fields are wrong by seeing red border indicator

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4636
- [ ] https://github.com/saleor/saleor-dashboard/issues/4637
- [ ] https://github.com/saleor/saleor-dashboard/issues/4638
- [ ] https://github.com/saleor/saleor-dashboard/issues/4640
- [ ] https://github.com/saleor/saleor-dashboard/issues/4645
- [ ] https://github.com/saleor/saleor-dashboard/issues/4646
- [ ] https://github.com/saleor/saleor-dashboard/issues/4649
- [ ] https://github.com/saleor/saleor-dashboard/issues/4665
```
