### ISSUE TITLE
[Feature]: Gift reward

### ISSUE THREAD

**Issue by poulch** [saleor/saleor-dashboard#4651]
### Description of the feature

Users will be able to select any product variant as gift card reward. User should choose between subtotal price discount reward and gift card.

AC:
- User should be able to select between subtotal and gift reword
- User should be able to select one or more product variant  as gift
- User should see if order line item has been select as gift in order details

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/issues/4652
- [ ] https://github.com/saleor/saleor-dashboard/issues/4653
- [ ] https://github.com/saleor/saleor-dashboard/issues/4656
```
